image: openjdk:8

before_script:
  # Enable the usage of sources over https
  - apt-get update -yqq
  - apt-get install apt-transport-https -yqq
  # Add keyserver for SBT
  - echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
  # Install SBT
  - apt-get update -yqq
  - apt-get install sbt -yqq

  # Log the sbt version
  - sbt sbtVersion

test:
  script:
    # Execute your project's tests
    - sbt clean test